name: Daily Auto Commit

on:
  schedule:
    - cron: "0 * * * *"  # Every hour, on the hour (UTC)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure file exists
        run: |
          touch index.html

      - name: Append update with IST timestamp
        run: |
          TZ="Asia/Kolkata" date +"<!-- Auto update at %Y-%m-%d %H:%M:%S IST -->" >> index.html

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push if there are changes
        run: |
          git add index.html
          git diff --cached --quiet && echo "No changes to commit" || (
            git commit -m "Automated daily commit from GitHub Actions"
            git push origin HEAD
          )
